import jsPDF from 'jspdf';
import { AnalysisResult } from '@/types/analysis';
import { getRatioInfos } from '@/lib/calculations';

export function generateAnalysisPDF(analysis: AnalysisResult) {
  const doc = new jsPDF();
  const ratios = getRatioInfos(analysis.ratios);
  const d = analysis.balanceSheetData;
  const ai = analysis.aiAnalysis;
  let y = 20;

  const addLine = (text: string, size = 11, bold = false) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setFontSize(size);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.text(text, 15, y);
    y += size * 0.5 + 3;
  };

  const addWrapped = (text: string, size = 10) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(text, 180);
    for (const line of lines) {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(line, 15, y);
      y += size * 0.45 + 2;
    }
  };

  // Header
  addLine('Financial Analysis Report', 18, true);
  addLine(d.companyName + (d.tickerSymbol ? ` (${d.tickerSymbol})` : ''), 14, true);
  addLine(d.analysisPeriod || new Date(analysis.createdAt).toLocaleDateString(), 10);
  y += 5;

  // Balance Sheet
  doc.setDrawColor(59, 130, 246);
  doc.line(15, y, 195, y);
  y += 8;
  addLine('Balance Sheet Data', 13, true);
  const bsItems = [
    ['Total Assets', d.totalAssets],
    ['Total Liabilities', d.totalLiabilities],
    ['Current Assets', d.currentAssets],
    ['Current Liabilities', d.currentLiabilities],
    ['Total Equity', d.totalEquity],
    ['Total Debt', d.totalDebt],
  ] as const;
  for (const [label, val] of bsItems) {
    addLine(`${label}: $${val.toLocaleString()}`, 10);
  }
  y += 5;

  // Ratios
  doc.line(15, y, 195, y);
  y += 8;
  addLine('Financial Ratios', 13, true);
  for (const r of ratios) {
    addLine(`${r.name}: ${r.formatted} — ${r.interpretation}`, 10);
  }
  y += 5;

  // AI Analysis
  if (ai) {
    doc.line(15, y, 195, y);
    y += 8;
    addLine('AI Analysis', 13, true);
    addLine(`Recommendation: ${ai.recommendation}`, 12, true);
    addLine(`Risk Score: ${ai.riskScore}/100 | Confidence: ${ai.confidenceLevel}%`, 10);
    y += 3;
    addLine('Executive Summary:', 11, true);
    addWrapped(ai.summary);
    y += 3;

    if (ai.strengths.length) {
      addLine('Strengths:', 11, true);
      for (const s of ai.strengths) addLine(`• ${s}`, 10);
    }
    if (ai.weaknesses.length) {
      addLine('Weaknesses:', 11, true);
      for (const w of ai.weaknesses) addLine(`• ${w}`, 10);
    }
    y += 3;
    addLine('Detailed Reasoning:', 11, true);
    addWrapped(ai.reasoning);
  }

  // Footer
  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Generated by AI Investment Analyzer — ${new Date().toLocaleString()}`, 15, 285);

  doc.save(`${d.companyName.replace(/\s+/g, '_')}_analysis.pdf`);
}
